name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04

    steps:
      - name: Check the repository
        uses: actions/checkout@v2

      # Sets up Libindy.
      - name: Setup Libindy
        uses: ./.github/actions/setup-libindy

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Installing the project dependencies
      - name: Install dependencies
        run: yarn install

      # Validation
      - name: Running `yarn validate`
        run: yarn validate

      # Run the tests
      - name: Run tests with coverage
        run: yarn test --coverage
