name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-20.04

    steps:
      - name: Check the repository
        uses: actions/checkout@v2

      - name: Validate
        uses: ./.github/actions/validate
        with:
          node-version: 16.x
          uses-libindy: true

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-20.04

    steps:
      - name: Check the repository
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test
        with:
          node-version: 16.x
          uses-libindy: true
