name: Build and Deploy Stack

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the image'
        required: true
        type: string

jobs:
  build_and_deploy:
    name: Build and Deploy Stack
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Template Stack
        uses: ./.github/actions/deploy
        env:
          WALLET_KEY: ${{ secrets.WALLET_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE_URL: ${{ secrets.POSTGRES_DATABASE_URL }}
          POSTGRES_ADMIN_USER: ${{ secrets.POSTGRES_ADMIN_USER }}
          POSTGRES_ADMIN_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          POSTGRES_TLS_CA: ${{ secrets.POSTGRES_TLS_CA }}
        with:
          envs: WALLET_KEY,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DATABASE_URL,POSTGRES_ADMIN_USER,POSTGRES_ADMIN_PASSWORD,POSTGRES_TLS_CA
          stack-name: animo-afj-mediator
          stack-file: ./docker-compose-animo-mediator.yml
          private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
